version: 0.2
phases:
  install:
    commands:
      - npm i -g npm
      - npm i -g serverless
  build:
    commands:
      - cd app
      - npm ci
      - export SLS_DEBUG="*"
      - export AWSJS_DEBUG="*"
      - serverless deploy --verbose --region ${AWS_REGION} --environment ${AWS_ENV}
